require_relative 'tasks/lint'
require_relative 'tasks/optimise'
require_relative 'tasks/idiomise'
require_relative 'tasks/format'
require_relative 'tasks/pedantise'
require_relative 'tasks/check'
require_relative 'tasks/build'
